# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ad0dcb572ba3d239e44e2601546c94c669eb2b346ce7d492ce254d2c3911481914515bffea1efd1e8e1963ad5df052dc86db2a75556c902af2cc4578b60690

test:
  secret_key_base: 2caa67983a5e1a886446f5987302622ab00913de11427680e70387cc7a7205cfeef59095c60adb460b8dce98be0fea240cc8f9619e17ae0ebbba5e4fe66429f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
